PSPSDK := $(shell psp-config --pspsdk-path)

TARGET := swdec-meload
OBJS := main.o mestub.o
VPATH := $(MELOAD_SOURCE_DIR)
CFLAGS := -O2 -G0 -Wall -fno-builtin
ASFLAGS := $(CFLAGS)
BUILD_PRX := 1
PRX_EXPORTS := exports.exp
USE_KERNEL_LIBC := 1
USE_KERNEL_LIBS := 1
LIBS := -lpspkernel
EXTRA_TARGETS := swdec-meload.prx

include $(PSPSDK)/lib/build.mak
