#!/usr/bin/env python3
"""Generate src/psp_crypto_selftest_vectors.h.

The products are computed by CPython's arbitrary-precision integers --
an implementation with nothing in common with mbed TLS's bignum, on a
different CPU, in a different language. That independence is the point:
these are the vectors that catch a carry bug mbed TLS's own selftests
would agree with themselves about.
"""
import sys

M32 = (1 << 32) - 1

vectors = []


def add(name, a, b):
    vectors.append((name, a, b, a * b))


add("one_limb", 0xFFFFFFFF, 0xFFFFFFFF)
add("two_limb_saturated", (1 << 64) - 1, (1 << 64) - 1)
add("carry_cascade", (1 << 256) - 1, 0xFFFFFFFF)
# 8 limbs exactly: one full X8 batch, zero X1 remainder.
add("x8_exact", (1 << 256) - 1, (1 << 256) - 1)
# 9 limbs: one X8 batch plus a single X1 step.
add("x8_plus_one", (1 << 288) - 1, (1 << 288) - 1)
# 7 limbs: X1 remainder path only, no X8 batch at all.
add("x1_only", (1 << 224) - 1, (1 << 224) - 1)
# Alternating bit patterns: every limb straddles a half-word boundary.
add("alternating", int("A5" * 64, 16), int("5A" * 64, 16))
# The NIST P-256 prime squared -- the value the ECP reduction actually
# grinds on during a handshake.
P256 = 2**256 - 2**224 + 2**192 + 2**96 - 1
add("p256_prime_square", P256, P256)
# RSA-2048 shape: two 2048-bit saturated operands. The worst carry case
# at the size the updater's signature verify uses.
add("rsa2048_saturated", (1 << 2048) - 1, (1 << 2048) - 1)
# A 2048-bit multiply with pseudo-random limbs, matching the timing loop
# operands exactly so the timed path is also a checked path.
a = 0
b = 0
for i in range(64):
    a |= ((0x9E3779B9 * (i + 1)) & M32) << (32 * i)
    b |= ((0x85EBCA6B ^ (i * 7 + 3)) & M32) << (32 * i)
a |= 1 << 2047
b |= 1 << 2047
add("rsa2048_timing_operands", a, b)

out = []
out.append("/* Generated by tests/gen_bn_mul_vectors.py")
out.append(" * (see the key-exchange contract in docs/engineering/PSP_TRANSPORT.md).")
out.append(" *")
out.append(" * Known-answer vectors for mbedtls_mpi_mul_mpi. The products were")
out.append(" * computed by CPython's arbitrary-precision integers on the host --")
out.append(" * a wholly independent implementation -- so agreement here is a")
out.append(" * statement about mbed TLS's bignum being right, not merely")
out.append(" * self-consistent. Sizes are chosen to cover the X8-batch path, the")
out.append(" * X1-remainder path, and the boundary between them, with saturated")
out.append(" * limbs wherever a carry can cascade.")
out.append(" *")
out.append(" * Do not hand-edit: regenerate.")
out.append(" */")
out.append("")
out.append("static const struct mul_vector mul_vectors[] = {")
for name, a, b, p in vectors:
    out.append("    {")
    out.append('        "%s",' % name)
    out.append('        "%X",' % a)
    out.append('        "%X",' % b)
    out.append('        "%X",' % p)
    out.append("    },")
out.append("};")
out.append("")

sys.stdout.write("\n".join(out))
