/* Layout suite: responsive CSS, layout algorithms, painting, and
   fonts.  Split out of test_tilefinch.c so layout tests live beside the
   layout translation units they exercise. */

#include "tilefinch_test_common.h"
#include "../src/style_internal.h"

typedef enum {
    DEEP_LAYOUT_BLOCK,
    DEEP_LAYOUT_INLINE,
    DEEP_LAYOUT_FLEX_INTRINSIC
} DeepLayoutMode;

static const char responsive_page[] =
    "<!doctype html><title>Responsive</title><style>"
    ":root{--card-gap:12px;--ink:#123456;--important-edge:6px}"
    ".cards{display:flex;display:-ms-flexbox;gap:var(--card-gap,4px);color:var(--ink,#000);padding:2px;align-items:center;justify-content:center;min-height:50px;word-spacing:1px}"
    ".card,.alternate{display:block;background:#eeeeee;margin:2px}"
    ".alternate{position:relative;left:3px;top:-2px}"
    ".card{flex:1 1 40%;border-bottom:2px solid #010203}"
    ".cards .card.alternate{color:#abcdef}"
    ".cards:has(.alternate:not(.missing)){border-top:3px solid #0a0b0c}"
    ".wrong .card.alternate{display:none}"
    ".cards > article.card{padding-left:9px}"
    ".cards .alternate span{visibility:hidden}"
    ".cards .card em{position:absolute}"
    "#pixel{display:block;width:4px;height:2px;object-fit:cover}"
    ".empty-slot:empty{display:none}"
    ".card:not(.alternate){margin-top:11px}"
    ".card:is(.alternate,.missing){margin-bottom:13px}"
    ".icon{display:inline-block;width:20px;height:20px;min-width:18px;flex:none;margin:0 auto;mask-image:url(https://example.com/icon.svg)}"
    ".icon::after{content:\"\";position:absolute;right:0;top:0;width:4px;height:4px;background:#00ff00;mask-image:url(https://example.com/badge.svg)}"
    "ul{list-style:none}ol{margin-left:20px}"
    ".card::before{display:none}"
    ".cards::after{content:\"\";position:absolute;left:3px;right:4px;bottom:2px;height:1px;background:#ff0000}"
    ".sticky{position:sticky;top:12px;background:#445566}"
    ".fixed{position:fixed;top:20px;width:40px;height:20px;background:#778899}"
    ".rounded{width:30px;height:20px;background:#112233;border-radius:8px}"
    ".tail{height:400px}"
    ".matrix tbody{display:block}.matrix tr{display:table-row}"
    ".matrix th,.matrix td{display:table-cell}"
    ".centered{width:200px;text-align:center}"
    ".nowrap{width:40px;white-space:nowrap}"
    ".grid{display:grid;grid-template-columns:repeat(2,1fr);"
    "gap:6px 10px;width:200px}"
    ".grid>div{display:block;height:20px}"
    ".fluid{display:block;width:clamp(100px,50vw,300px);"
    "height:min(40px,10vh);margin-left:calc(10px + 5px);"
    "font-size:clamp(12px,3vw,20px)}"
    ".spaced{display:flex;width:200px;justify-content:space-between}"
    ".spaced>span{display:block;width:20px}"
    ".wrap-grow{display:flex;flex-wrap:wrap;width:100px;column-gap:4px;row-gap:7px}"
    ".wrap-grow>span{display:block;flex:1 1 40px;height:10px}"
    ".wrap-space{display:flex;flex-wrap:wrap;width:100px;column-gap:4px;row-gap:9px;justify-content:space-between}"
    ".wrap-space>span{display:block;flex:0 0 40px;height:10px}"
    ".explicit-grow{display:flex;width:100px}"
    ".explicit-grow>span{display:block;width:20px;height:10px;flex-grow:1}"
    ".explicit-grow>#explicit-grow-b{flex-grow:3}"
    ".flex-table-cells{display:flex;width:200px}"
    ".flex-table-cells>span{display:table-cell;flex:1 0;height:10px}"
    ".weighted-shrink{display:flex;width:120px}"
    ".weighted-shrink>span{display:block;width:60px;height:10px;"
    "flex-shrink:1;min-width:0}"
    ".weighted-shrink>#shrink-a{flex-shrink:0}"
    ".weighted-shrink>#shrink-c{flex-shrink:2}"
    ".anywhere-wrap{display:block;width:40px;overflow-wrap:anywhere}"
    ".break-all-wrap{display:block;width:40px;word-break:break-all}"
    ".content-box-flex,.border-box-flex{display:flex;width:80px}"
    ".content-box-flex>span{display:block;flex:0 0 auto;width:20px;padding:0 5px;border-left:2px solid #111;border-right:2px solid #111;margin:0 3px}"
    ".border-box-flex>span{display:block;flex:0 0 auto;box-sizing:border-box;width:30px;padding:0 5px;border-left:2px solid #111;border-right:2px solid #111;margin:0 5px}"
    ".column-align{display:flex;flex-direction:column;width:100px;gap:7px;align-items:center}"
    ".column-align>span{display:block;width:20px;height:10px}"
    ".column-end{display:flex;flex-direction:column;width:100px;align-items:end}"
    ".column-end>span{display:block;width:20px;height:10px;margin-right:3px}"
    ".column-between{display:flex;flex-direction:column;width:40px;height:100px;justify-content:space-between}"
    ".column-between>span{display:block;height:10px}"
    ".column-center{display:flex;flex-direction:column;width:40px;height:100px;justify-content:center}"
    ".column-center>span{display:block;height:10px}"
    ".tracking{letter-spacing:3px}"
    ".grid-remainder{display:grid;grid-template-columns:repeat(3,1fr);gap:2px;width:101px}"
    ".grid-remainder>span{display:block;height:5px}"
    ".ratio{display:block;width:160px;aspect-ratio:16 / 9;background:center/cover no-repeat #202020 url(https://example.com/background.png)}"
    ".explicit-background{display:block;width:120px;height:60px;"
    "background-image:url(https://example.com/logo.png);"
    "background-size:82px 20px;background-position:50%;"
    "text-indent:-9999px}"
    ".pseudo-background{display:block;width:120px}"
    ".pseudo-background::before{content:\"\";display:block;width:100%;"
    "padding-top:40px;background-color:#123abc;"
    "background-image:url(https://example.com/crest.svg);"
    "background-size:30px 20px;background-position:50% 0%}"
    ".sibling-a + .sibling-b{color:#314159}"
    ".sibling-a ~ .sibling-c{background:#271828}"
    ".nth-list>li:nth-child(2n+1){color:#102938}"
    ".nth-list>li:nth-of-type(even){background:#475869}"
    ".nth-list>li:first-of-type{border-left:1px solid #556677}"
    ".nth-list>li:last-of-type{border-right:2px solid #556677}"
    ".nth-list>li:nth-last-child(2){border-top:3px solid #556677}"
    "#only-wrap>b:only-child,#mixed>span:only-of-type{border-bottom:4px solid #765432}"
    "button:disabled{opacity:.25}button:enabled{background:#135724}"
    "input:checked{border-left:2px solid #abcdef}"
    "input:required{border-bottom:3px solid #abcdef}"
    "input:optional{border-top:1px solid #abcdef}"
    "a:any-link{border-right:2px solid #abcdef}"
    "#focus-probe:focus{color:#2468ac}#focus-probe:focus-visible{border-left:3px solid #13579b}"
    "#focus-host:focus-within{background:#abcdef}"
    ".variable-scope{--accent:#224466;--base-edge:5px;--edge:var(--base-edge)}"
    ".variable-scope .variable-child{color:var(--accent);border-left:var(--edge) solid var(--accent);padding-left:calc(var(--edge) + 2px)}"
    ".fallback-variable{color:var(--missing,#112244)}"
    ".logical-box{position:absolute;margin-inline:auto 6px;padding-block:3px 4px;inset-inline:7px 9px;inset-block:11px 13px;border-inline:2px solid #456789;border-block-start:3px solid #456789;border-block-end-width:4px}"
    ".important{color:#111111 ! important;background:#111111 !/**/IMPORTANT;padding-left:var(--important-edge)!important;padding-left:1px}"
    "#important{color:#999999;background:#999999}"
    "#specificity{color:#111111}"
    ":where(#specificity).specificity{color:#222222}"
    ".specificity:is(#specificity,.other){background:#333333}"
    "#specificity{background:#444444}"
    ".specificity:not(.missing){border-left:2px solid #123456}"
    ".specificity{border-left:1px solid #654321}"
    "#specificity-heavy{color:#123456}"
    ".a.a.a.a.a.a.a.a.a.a.a{color:#654321}"
    "@layer reset,components;"
    "@layer reset{#layered{color:#111111!important;background:#111111;--layer-color:#111111}#var-layered{--priority-color:#110000!important}}"
    "@layer components{.layered{color:#222222!important;background:#222222;--layer-color:#222222}#var-layered{--priority-color:#220000!important}}"
    "#layered{color:#333333!important;background:#333333;--layer-color:#334455;border-left:3px solid var(--layer-color)}"
    "#var-layered{--priority-color:#330000!important;color:var(--priority-color)}"
    "#var-inline{--inline-color:#111100!important;color:var(--inline-color)}"
    "#var-user,#var-user-important{--user-color:#111111!important;color:var(--user-color)}"
    ".modern-rgb{color:rgb(10 20 30 / 100%)}"
    ".modern-hsl{color:hsl(120deg 100% 25%)}"
    ".modern-oklch{color:oklch(63.7% 0.237 25.331)}"
    ".alpha-zero{background-color:rgb(1 2 3 / 0%)}"
    ".hex-alpha{color:#abcd}"
    ".partial-alpha{display:block;color:rgb(255 0 0 / 50%);background:rgb(0 0 255 / 25%);border-left:4px solid rgb(4 250 128 / 75%)}"
    ".generated{display:block}.generated::before{content:\"Ask \\41 nything \\2713\";color:#214365;background:#edf1f5;padding:2px}"
    ".attr-generated{display:block}.attr-generated::after{content:attr(data-label);color:#365214}"
    "[data-route^=chat][data-route$=end][data-route*=middle][lang|=en]{border-right:4px solid #246813}"
    "@supports (display:grid){.grid{background:#112244}}"
    "@supports (display:subgrid){.grid{display:none}}"
    "@supports not (display:subgrid){.grid{border-left:2px solid #334455}}"
    "@media (orientation:landscape) and (hover:none) and (pointer:coarse)"
    "{.grid{opacity:.5}}"
    "@media (orientation:portrait){.grid{display:none}}"
    "@media (max-width:600px){.cards{padding:1rem}}"
    "@media (min-width:700px){.cards{display:none}}"
    "@media (prefers-color-scheme: dark){:root{--ink:#000000}}"
    ".reduced-motion{opacity:0}"
    "@media (prefers-reduced-motion:reduce){.reduced-motion{opacity:1}}"
    "@media (prefers-reduced-motion:no-preference){.reduced-motion{display:none}}"
    "</style><body><main id=cards class=cards>"
    "<article id=left class=card>LEFT <span id=icon class=icon></span><em>OFFFLOW</em></article>"
    "<article id=right class='card alternate'>RIGHT <picture><source "
    "srcset='small.png 320w, large.png 640w'><img id=pixel width=2 "
    "height=2 alt=P></picture> <span>HIDDEN</span></article>"
    "</main><div id=sticky class=sticky>STICKY</div>"
    "<div id=fixed class=fixed>FIXED</div><div id=rounded class=rounded></div><div class=tail>TAIL</div>"
    "<p><span>ADJ</span><b>ACENT</b> BASE<sup>2</sup></p>"
    "<table class=matrix><tbody><tr><th>KEY</th><td>VALUE</td></tr></tbody></table>"
    "<ul><li id=nobullet>NOBULLET</li></ul>"
    "<ol><li>ORDEREDONE</li><li>ORDEREDTWO</li></ol>"
    "<p data-placeholder='TYPE HERE'><br></p>"
    "<div id=centered class=centered>CENTERED</div>"
    "<div id=nowrap class=nowrap>FIRST SECOND</div>"
    "<div id=grid class=grid><div id=grid-a>GRID-A</div>"
    "<div id=grid-b>GRID-B</div><div id=grid-c>GRID-C</div></div>"
    "<div id=fluid class=fluid>FLUID</div>"
    "<div id=reduced-motion class=reduced-motion>REDUCED</div>"
    "<div id=spaced class=spaced><span id=space-a>SPACE-A</span>"
    "<span id=space-b>SPACE-B</span></div>"
    "<div id=wrap-grow class=wrap-grow><span id=grow-a>GA</span>"
    "<span id=grow-b>GB</span><span id=grow-c>GC</span></div>"
    "<div id=wrap-space class=wrap-space><span id=justify-a>JA</span>"
    "<span id=justify-b>JB</span><span id=justify-c>JC</span></div>"
    "<div class=explicit-grow><span id=explicit-grow-a>EA</span>"
    "<span id=explicit-grow-b>EB</span></div>"
    "<div class=flex-table-cells><span id=flex-table-cell-a>FTA</span>"
    "<span id=flex-table-cell-b>FTB</span></div>"
    "<div class=weighted-shrink><span id=shrink-a>SA</span>"
    "<span id=shrink-b>SB</span><span id=shrink-c>SC</span></div>"
    "<div id=anywhere-wrap class=anywhere-wrap><span>WWWWWWWWWWWWWW</span></div>"
    "<div id=break-all-wrap class=break-all-wrap><span>QQQQQQQQQQQQQQ</span></div>"
    "<div class=content-box-flex><span id=content-box-a>CA</span>"
    "<span id=content-box-b>CB</span></div>"
    "<div class=border-box-flex><span id=border-box-a>BA</span>"
    "<span id=border-box-b>BB</span></div>"
    "<div id=column-align class=column-align><span id=column-a>COA</span>"
    "<span id=column-b>COB</span></div>"
    "<div id=column-end class=column-end><span id=column-end-item>COE</span></div>"
    "<div id=column-between class=column-between><span id=column-between-a>CBA</span>"
    "<span id=column-between-b>CBB</span></div>"
    "<div id=column-center class=column-center><span id=column-center-item>"
    "<a id=column-center-link href=/center>CCI</a></span></div>"
    "<div class=tracking><span id=tracking-child>ZZZZZ</span></div>"
    "<div>ZZZZZ</div>"
    "<div id=grid-remainder class=grid-remainder><span id=grid-rem-a>GRA</span>"
    "<span id=grid-rem-b>GRB</span><span id=grid-rem-c>GRC</span></div>"
    "<div id=ratio class=ratio></div>"
    "<div id=explicit-background class=explicit-background>BRAND</div>"
    "<div id=pseudo-background class=pseudo-background></div>"
    "<div class=sibling-a>A</div><div id=sibling-b class=sibling-b>B</div>"
    "<div id=sibling-c class=sibling-c>C</div>"
    "<ul class=nth-list><li id=nth-one>ONE</li><li id=nth-two>TWO</li>"
    "<li id=nth-three>THREE</li></ul>"
    "<div id=attribute-operators data-route=chat-middle-end lang=en-US>ATTRIBUTES</div>"
    "<div id=only-wrap><b id=only-child>ONLY</b></div>"
    "<div id=mixed><i>MIXED</i><span id=only-type>TYPE</span></div>"
    "<button id=disabled-control disabled>DISABLED</button>"
    "<button id=enabled-control>ENABLED</button>"
    "<input id=checked-control checked required>"
    "<input id=optional-control>"
    "<a id=any-link href=/target>LINK</a>"
    "<div id=focus-host><input id=focus-probe data-tilefinch-focus></div>"
    "<div class=variable-scope style='--accent:#335577'><span id=variable-child class=variable-child>VARIABLE</span></div>"
    "<span id=fallback-variable class=fallback-variable>FALLBACK</span>"
    "<div id=logical-box class=logical-box>LOGICAL</div>"
    "<div id=important class=important style='color:#222222;background:#333333 !IMPORTANT'>IMPORTANT</div>"
    "<div id=specificity class=specificity>SPECIFICITY</div>"
    "<div id=specificity-heavy class=a>HEAVY SPECIFICITY</div>"
    "<div id=layered class=layered>LAYERED</div>"
    "<div id=var-layered>VARLAYERED</div>"
    "<div id=var-inline style='--inline-color:#222200 !IMPORTANT;--inline-color:#333300'>VARINLINE</div>"
    "<div id=var-user>VARUSER</div>"
    "<div id=var-user-important>VARUSERIMPORTANT</div>"
    "<span id=modern-rgb class=modern-rgb>RGB</span>"
    "<span id=modern-hsl class=modern-hsl>HSL</span>"
    "<span id=modern-oklch class=modern-oklch>OKLCH</span>"
    "<span id=alpha-zero class=alpha-zero>ALPHA</span>"
    "<span id=hex-alpha class=hex-alpha>HEXALPHA</span>"
    "<div id=partial-alpha class=partial-alpha>PARTIAL</div>"
    "<div id=generated class=generated>HOST</div>"
    "<div id=attr-generated class=attr-generated data-label='Live label'>ATTRHOST</div>"
    "<div id=empty-slot class=empty-slot></div>"
    "<i id=slant>ITALIC</i></body>";


/* Focused helpers and the long integration inventory remain one translation
   unit, but live in ownership-oriented files for faster review. */
#include "suites/layout_flow.inc"
#include "suites/layout_paint.inc"
#include "suites/layout_structure.inc"

static int test_layout(void)
{
#include "suites/layout_regression_1.inc"
#include "suites/layout_regression_structure.inc"
#include "suites/layout_regression_positioning.inc"
#include "suites/layout_regression_fonts.inc"

int main(void)
{
    setvbuf(stdout, NULL, _IONBF, 0);
    return test_layout();
}
