PSPSDK := $(shell psp-config --pspsdk-path)

TARGET := tilefinch-swdec
OBJS := swdec_component_psp.o swdec.o swdec_arena.o swdec_me.o \
        swdec_meload.o
INCDIR := $(SWDEC_SOURCE_DIR) $(TILEFINCH_SOURCE_DIR)/include \
          $(TILEFINCH_SOURCE_DIR)/src \
          $(FFMPEG_SOURCE_DIR)
LIBDIR := $(FFMPEG_LIBRARY_DIR)
VPATH := $(SWDEC_SOURCE_DIR)
CFLAGS := -O2 -G0 -Wall -Wextra -std=gnu11 -DPSP \
          -DHAVE_AV_CONFIG_H -DSWDEC_ME=1 -DSWDEC_ME_DEBLOCK=1 \
          -DSWDEC_FRAME_ONLY=1 -DSWDEC_PSP_ASM=1 \
          -DSWDEC_LF_STRENGTH_C=1 -DSWDEC_PSP_LF_CHROMA=1
ASFLAGS := $(CFLAGS)
LIBS := -lavcodec -lavutil -lpspsdk -lm
BUILD_PRX := 1
EXTRA_TARGETS := tilefinch-swdec.prx

include $(PSPSDK)/lib/build.mak
