#!/usr/bin/env python3
"""Generate src/text_encoding_tables.inc from the WHATWG Encoding Standard.

usage: gen-text-encoding-tables.py DATA_DIR > src/text_encoding_tables.inc

DATA_DIR holds the standard's encodings.json and its single-byte index files
(index-<name>.txt), for example Lexbor's copy in
build-preset-release/_deps/lexbor-src/utils/lexbor/encoding (encodings.json
plus single-byte/). Only decoders Tilefinch implements get an id: UTF-8,
every legacy single-byte encoding, UTF-16BE/LE, replacement and
x-user-defined. Labels of the multi-byte CJK encodings map to
TILEFINCH_ENCODING_UNSUPPORTED so a page naming one keeps the UTF-8
fallback rather than a wrong single-byte decode.
"""
import json
import os
import sys

FIXED = {
    "UTF-8": "TILEFINCH_ENCODING_UTF8",
    "UTF-16BE": "TILEFINCH_ENCODING_UTF16BE",
    "UTF-16LE": "TILEFINCH_ENCODING_UTF16LE",
    "replacement": "TILEFINCH_ENCODING_REPLACEMENT",
    "x-user-defined": "TILEFINCH_ENCODING_X_USER_DEFINED",
}


# Labels the standard added after the copy of encodings.json that Lexbor
# v3.0.0 ships (its index files are dated 2018-01-06).
LATER_LABELS = {
    "UTF-8": ["unicode11utf8", "unicode20utf8", "x-unicode20utf8"],
    "UTF-16BE": ["unicodefffe"],
    "UTF-16LE": ["csunicode", "iso-10646-ucs-2", "ucs-2", "unicode",
                 "unicodefeff"],
}


def index_path(root, name):
    for sub in ("", "single-byte"):
        path = os.path.join(root, sub, "index-%s.txt" % name.lower())
        if os.path.exists(path):
            return path
    raise SystemExit("missing index for " + name)


def read_index(path):
    table = [0] * 128
    for line in open(path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        pointer, code = line.split()[:2]
        pointer, code = int(pointer), int(code, 16)
        if not 0 <= pointer < 128 or not 0 < code <= 0xFFFF:
            raise SystemExit("unexpected index entry: " + line)
        table[pointer] = code
    return table


def main():
    root = sys.argv[1]
    groups = json.load(open(os.path.join(root, "encodings.json")))
    single = []
    labels = []
    for group in groups:
        for encoding in group["encodings"]:
            name = encoding["name"]
            if group["heading"] == "Legacy single-byte encodings":
                single.append(name)
                ident = len(single)
            elif name in FIXED:
                ident = FIXED[name]
            else:
                ident = "TILEFINCH_ENCODING_UNSUPPORTED"
            for label in encoding["labels"] + LATER_LABELS.get(name, []):
                if label not in (known[0] for known in labels):
                    labels.append((label, ident))
    # ISO-8859-8-I decodes with the ISO-8859-8 index.
    tables, table_of = [], {}
    for name in single:
        source = "ISO-8859-8" if name == "ISO-8859-8-I" else name
        if source not in table_of:
            table_of[source] = len(tables)
            tables.append((source, read_index(index_path(root, source))))
        table_of[name] = table_of[source]
    labels.sort()
    out = sys.stdout
    out.write("/* Generated by tools/gen-text-encoding-tables.py from the WHATWG\n"
              "   Encoding Standard (encodings.json and its single-byte indexes).\n"
              "   Do not edit by hand. */\n\n")
    out.write("#define TILEFINCH_SINGLE_BYTE_ENCODING_COUNT %du\n\n" % len(single))
    out.write("static const char *const single_byte_names[%d] = {\n" % len(single))
    for name in single:
        out.write('    "%s",\n' % name)
    out.write("};\n\n")
    out.write("static const uint8_t single_byte_table[%d] = {\n    " % len(single))
    out.write(", ".join(str(table_of[n]) for n in single))
    out.write("\n};\n\n")
    out.write("/* Code points for bytes 0x80-0xFF; 0 is an unmapped byte. */\n")
    out.write("static const uint16_t single_byte_index[%d][128] = {\n" % len(tables))
    for source, table in tables:
        out.write("    { /* %s */\n" % source)
        for row in range(0, 128, 8):
            out.write("        " + ", ".join("0x%04X" % v for v in table[row:row + 8]) + ",\n")
        out.write("    },\n")
    out.write("};\n\n")
    out.write("/* Sorted labels; label_ids holds the encoding of each. */\n")
    out.write("static const char encoding_labels[] =\n")
    for label, _ in labels:
        out.write('    "%s\\0"\n' % label)
    out.write("    ;\n\n")
    out.write("static const uint8_t encoding_label_ids[%d] = {\n" % len(labels))
    for label, ident in labels:
        out.write("    %s, /* %s */\n" % (ident, label))
    out.write("};\n")


if __name__ == "__main__":
    main()
