#!/usr/bin/env python3
"""Generate bounded, data-only locale downloads and their EBOOT trust pins."""
import argparse
import hashlib
from pathlib import Path
from devanagari_sequences import encoded as hindi_sequences

ROOT = Path(__file__).resolve().parents[1]
CATALOGS = [(1, [("es", "Spanish", "EMBEDDED"), ("fr", "French", "EMBEDDED"),
                 ("de", "German", "EMBEDDED"), ("ja", "Japanese", "JAPANESE")]),
            (2, [("ru", "Russian", "CYRILLIC"), ("uk", "Ukrainian", "CYRILLIC"),
                 ("zh-hans", "Chinese (Simplified)", "CHINESE_SIMPLIFIED"),
                 ("ko", "Korean", "KOREAN")]),
            (3, [("hi", "Hindi", "DEVANAGARI"),
                 ("ar", "Arabic", "ARABIC")]),
            (4, [("es", "Spanish", "EMBEDDED"), ("fr", "French", "EMBEDDED"),
                 ("de", "German", "EMBEDDED"), ("ja", "Japanese", "JAPANESE"),
                 ("ru", "Russian", "CYRILLIC"), ("uk", "Ukrainian", "CYRILLIC"),
                 ("zh-hans", "Chinese (Simplified)", "CHINESE_SIMPLIFIED"),
                 ("ko", "Korean", "KOREAN"), ("hi", "Hindi", "DEVANAGARI"),
                 ("ar", "Arabic", "ARABIC")])]
ACTIVE_VERSION = 4

def read_rows(version, languages):
    source = ROOT / f"translations/ui/v{version}/source.tsv"
    lines = source.read_text(encoding="utf-8").splitlines()
    if lines[0] != "\t".join(["English"] + [label for _, label, _ in languages]):
        raise ValueError("unexpected language columns")
    rows = [line.split("\t") for line in lines[1:]]
    if not 0 < len(rows) <= 256 or any(len(r) != len(languages) + 1 for r in rows):
        raise ValueError("invalid row count or columns")
    rows.sort(key=lambda row: row[0].lower().encode("ascii"))
    if len({r[0].lower() for r in rows}) != len(rows):
        raise ValueError("duplicate English key")
    for row in rows:
        for value in row:
            if not value or len(value.encode("utf-8")) > 256 or "%" in value \
                    or any(ord(c) < 32 for c in value):
                raise ValueError("invalid display string")
    return rows

def outputs(resource_dir=None):
    result = {}
    manifest = ['/* Generated by tools/generate_ui_translations.py. */',
                'static const TilefinchUiLanguageSpec ui_languages[] = {',
                '    {"en", "English", BROWSER_GLYPH_LANGUAGE_EMBEDDED, NULL, 1, 0, NULL},']
    base_keys = None
    for version, languages in CATALOGS:
        rows = read_rows(version, languages)
        keys = {r[0].lower() for r in rows}
        if base_keys is not None and not base_keys <= keys:
            raise ValueError("new locales must translate every existing key")
        base_keys = keys
        for column, (code, label, glyphs) in enumerate(languages, 1):
            data = (f"TFUI1\t{code}\n" + "".join(
                f"{r[0]}\t{r[column]}\n" for r in rows)).encode("utf-8")
            if len(data) > 32768:
                raise ValueError("locale exceeds runtime bound")
            resource_key = f"translations/ui/v{version}/{code}.tful"
            if resource_dir is not None:
                result[resource_dir / resource_key] = data
            if version == ACTIVE_VERSION:
                minimum_glyph_sequence = 2 if glyphs == "DEVANAGARI" else 1
                manifest.append(f'    {{"{code}", "{label}", BROWSER_GLYPH_LANGUAGE_{glyphs}, '
                                f'"{hashlib.sha256(data).hexdigest()}", {version}, {minimum_glyph_sequence}, '
                                f'"{resource_key}"}},')
            if code == "hi":
                result[ROOT / f"translations/ui/v{version}/hi.sequences"] = \
                    hindi_sequences(r[column] for r in rows)
    manifest += ['};', '_Static_assert(sizeof(ui_languages) / sizeof(ui_languages[0])',
                 '    == TILEFINCH_UI_LANGUAGE_COUNT, "locale catalog mismatch");', '']
    result[ROOT / "src/generated/ui_languages.inc"] = "\n".join(manifest).encode()
    return result

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--resource-dir", type=Path,
                        help="export download/test data outside the source tree")
    parser.add_argument("--resources-only", action="store_true",
                        help="export resources but only verify committed pins/sequences")
    args = parser.parse_args()
    if args.resources_only and args.resource_dir is None:
        parser.error("--resources-only requires --resource-dir")
    if args.resource_dir is not None:
        args.resource_dir = args.resource_dir.resolve()
        if args.resource_dir in (ROOT, ROOT / "translations") or ROOT / "translations" in args.resource_dir.parents:
            parser.error("resource exports must not be stored in the authored translations tree")
    for path, data in outputs(args.resource_dir).items():
        resource = args.resource_dir is not None and args.resource_dir in path.parents
        if args.check or (args.resources_only and not resource):
            if not path.exists() or path.read_bytes() != data:
                raise SystemExit(f"stale UI translations: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists() or path.read_bytes() != data:
                path.write_bytes(data)
