# Script mode: embed a file as a C byte array header.
#   cmake -DINPUT=... -DOUTPUT=... -DNAME=... -P bin2c.cmake
if(NOT INPUT OR NOT OUTPUT OR NOT NAME)
    message(FATAL_ERROR "bin2c: INPUT, OUTPUT, and NAME are required")
endif()
file(READ "${INPUT}" hex_content HEX)
string(LENGTH "${hex_content}" hex_length)
math(EXPR byte_count "${hex_length} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex_content}")
string(REGEX REPLACE
    "(0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],0x[0-9a-f][0-9a-f],)"
    "\\1\n    " wrapped "${bytes}")
file(WRITE "${OUTPUT}" "/* Generated by cmake/bin2c.cmake from ${INPUT}. */
#include <stddef.h>

static const unsigned char ${NAME}[] = {
    ${wrapped}
};
static const size_t ${NAME}_length = ${byte_count};
")
